name: local_assets_server
description: HTTP Server which serves local assets
version: 1.0.3+7
homepage: https://github.com/lesnitsky/flutter_local_assets_server

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0
  mime: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
